# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: configserver-deployment
serviceName: configserver
appLabel: configserver
appName: configserver

replicaCount: 1

image:
  repository: danyashes/configserver
  tag: k8s-service-disc

containerPort: 9091

service:
  type: ClusterIP
  port: 9091
  targetPort: 9091

appname_enabled: true
profile_enabled: false
config_enabled: false
discovery_enabled: false
resouceserver_enabled: false
kafka_enabled: false
is_mysqldb: false
