# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: gatewayserver-deployment
serviceName: gatewayserver
appLabel: gatewayserver
appName: gatewayserver

replicaCount: 1

image:
  repository: danyashes/gatewayserver
  tag: k8s-service-disc

containerPort: 8095

service:
  type: LoadBalancer
  port: 8095
  targetPort: 8095

appname_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: true
kafka_enabled: false
is_mysqldb: false
