management:
    endpoint:
        shutdown:
            enabled: true
        health:
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
    info:
        env:
            enabled: true
    health:
        livenessstate:
            enabled: true
        readinessstate:
            enabled: true
    metrics:
        tags:
            application: ${spring.application.name}
spring:
    application:
        name: eurekaserver
    config:
        import: optional:configserver:http://localhost:9091/
