# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: mmdoctor-deployment
serviceName: mmdoctor
appLabel: mmdoctor
appName: mmdoctor

replicaCount: 1

image:
  repository: danyashes/mmdoctor
  tag: k8s-service-disc

containerPort: 8081

service:
  type: ClusterIP
  port: 8081
  targetPort: 8081

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
datasource_enabled: true
kafka_enabled: true
is_mysqldb: false
