endpoints:
    shutdown:
        enabled: true
eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:9111/eureka/
    instance:
        preferIpAddress: 'true '
info:
    app:
        description: Medione Patient Application
        name: Patient Microservice
        version: 1.0.0
management:
    endpoint:
        shutdown:
            enabled: true
        health:
            probes:
                enabled: true
    endpoints:
        web:
            exposure:
                include: '*'
    info:
        env:
            enabled: true
    health:
        livenessstate:
            enabled: true
        readinessstate:
            enabled: true
    metrics:
        tags:
            application: ${spring.application.name}
server:
    port: 8082
spring:
    application:
        name: mmpatient
    cache:
        type: NONE
    config:
        import: optional:configserver:http://localhost:9091
    datasource:
        password: root
        url: jdbc:mysql://127.0.0.10:3306/medione?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Europe/Moscow&useLegacyDatetimeCode=false
        username: root
    jpa:
        database-platform: org.hibernate.dialect.MySQLDialect
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                jdbc:
                    time_zone: Europe/Moscow
        show-sql: true
    profiles:
        active: prod
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
resilience4j.retry:
    configs:
        default:
            maxAttempts: 3
            waitDuration: 500
            enableExponentialBackoff: true
            exponentialBackoffMultiplier: 2