encrypt:
    key: medioneEncryptionCipherSymmetricKey
server:
    port: 9091
spring:
    application:
        name: configserver
    cloud:
        config:
            server:
                git:
                    clone-on-start: true
                    default-label: master
                    uri: https://github.com/danyash17/microservices-learning-config.git
    profiles:
        active: git
management:
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}