services:
  network-deploy-service:
    networks:
      medione:
  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
      
  microservice-configserver-dependant-config:
    extends:
      service: microservice-base-config
    depends_on:
      configserver:
        condition: service_healthy
    environment:
      SPRING_CONFIG_IMPORT: configserver:http://configserver:9091/
      SPRING_PROFILES_ACTIVE: dev
      
  microservice-configserver-eureka-dependant-config:
    extends:
      service: microservice-configserver-dependant-config
    depends_on:
      eurekaserver:
        condition: service_healthy
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:9111/eureka/
      
  microservice-full-backing-dependant-config:
    extends:
      service: microservice-configserver-eureka-dependant-config
    depends_on:
      medionemysqldb:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://medionemysqldb:3306/medione
      SPRING_RABBITMQ_HOST: rabbit