version: "3.8"

services:

  kafka:
    image: docker.io/bitnami/kafka:3.5
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
    extends:
      file: common-config.yml
      service: network-deploy-service

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak
    ports:
      - "7080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    extends:
      file: common-config.yml
      service: network-deploy-service

  medionemysqldb:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./dbdata:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medione
    extends:
      file: common-config.yml
      service: network-deploy-service

  configserver:
    image: danyashes/configserver:latest
    healthcheck:
      test: "curl --fail --silent localhost:9091/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 5s
    environment:
      SPRING_APPLICATION_NAME: "configserver"
    ports:
      - "9091:9091"
    extends:
      file: common-config.yml
      service: microservice-base-config

  gatewayserver:
    image: danyashes/gatewayserver:latest
    depends_on:
      mmdoctor:
        condition: service_healthy
      mmvisits:
        condition: service_healthy
      mmpatient:
        condition: service_healthy
    ports:
      - "8095:8095"
    environment:
      OTEL_SERVICE_NAME: "gatewayserver"
      SPRING_APPLICATION_NAME: "gatewayserver"
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI: "http://keycloak:8080/realms/master/protocol/openid-connect/certs"
    extends:
      file: common-config.yml
      service: microservice-configserver-eureka-dependant-config

  eurekaserver:
    image: danyashes/eurekaserver:latest
    ports:
      - "9111:9111"
    healthcheck:
      test: "curl --fail --silent localhost:9111/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
    environment:
      OTEL_SERVICE_NAME: "eurekaserver"
      SPRING_APPLICATION_NAME: "eurekaserver"
    extends:
      file: common-config.yml
      service: microservice-configserver-dependant-config

  mmpatient:
    image: danyashes/mmpatient:latest
    healthcheck:
      test: "curl --fail --silent localhost:8082/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 60s
    environment:
      SPRING_APPLICATION_NAME: "mmpatient"
    extends:
      file: common-config.yml
      service: microservice-full-backing-dependant-config

  mmdoctor:
    image: danyashes/mmdoctor:latest
    healthcheck:
      test: "curl --fail --silent localhost:8081/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 60s
    environment:
      SPRING_APPLICATION_NAME: "mmdoctor"
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "kafka:9092"
    extends:
      file: common-config.yml
      service: microservice-full-backing-dependant-config

  mmvisits:
    image: danyashes/mmvisits:latest
    healthcheck:
      test: "curl --fail --silent localhost:8083/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 30s
      retries: 15
      start_period: 60s
    environment:
      SPRING_APPLICATION_NAME: "mmvisits"
    extends:
      file: common-config.yml
      service: microservice-full-backing-dependant-config

  mmmessage:
    image: danyashes/mmmessage:latest
    environment:
      SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS: "kafka:9092"
    extends:
      file: common-config.yml
      service: network-deploy-service

networks:
  medione:
volumes:

  mysql_data:

  kafka_data:
      driver: local
